### ISSUE TITLE
Can't join to Session Open Group Channel

### ISSUE THREAD

**Issue by valsha** [oxen-io/session-website#15]
Good day, when I am trying to join [Session Open Group Channel.](https://getsession.org/session-open-group)
https://getsession.org/session-open-group

![image](https://user-images.githubusercontent.com/7966513/163343026-3673a7a5-e042-406c-9d9a-efbf8eb412b4.png)

**Error** - Please check the Session ID or ONS name and try again

Thank you.

**Comment by yougotwill** [comment]
Hi @valsha, I think you are trying to scan the QR code and adding a user and not joining an open group. When you choose the add option make sure to choose the open group option. I've updated the instructions on the website https://getsession.org/session-open-group

Let me know if you have any problems.
