### ISSUE TITLE
Session app deep-linking

### ISSUE THREAD

**Issue by legowerewolf** [oxen-io/session-website#21]
Not really sure the best place to put this, but: It would be nice if there was a way to create a sharable link to start a session with somebody. Basically the equivalent of t.me for Telegram.

**Comment by yougotwill** [comment]
Hey, thanks for posting! So deep links are a planned for later this year so I'll close this comment. You can probably look for progress later on in the iOS, Android or Desktop repositories. 😄

**Comment by legowerewolf** [comment]
Oh! Thank you!
