### ISSUE TITLE
[FIX] I restored using my recovery phrase but my contacts and messages are gone. What happened?

### ISSUE THREAD

**Issue by keybreak** [oxen-io/session-website#34]
https://getsession.org/faq#restored-contacts-and-messages

It's not particularly true lately, since you can retrieve all that with recovery phrase, probably needs to change to something like:
You have used **Clear Device and Network**

**Comment by Aerilym** [comment]
@keybreak Thanks for reporting this. The FAQ answer has now been updated with the appropriate copy changes.

See: https://getsession.org/faq#restored-contacts-and-messages
